name:     Mehakovic
markdown: redcarpet
pygments: true

assets:
  compress:
    css:  sass
    js:   uglifier

exclude: [todo.md, Gemfile, Gemfile.lock, Guardfile, config.ru, Procfile, readme.md, sass, unicorn.rb, vendor, log]

relative_permalinks: false
permalink: :title

cdn: http://www.cdn.mehakovic.com
url: http://www.mehakovic.com

service_deliverables_copy: "The deliverables can be in the form a presentation, a document, a log in protected section of my site or any of the above. The deliverables for this portion of work include:"