// Generated by CoffeeScript 1.6.3
(function() {
  $(document).ready(function() {
    var $input, $nav;
    $input = $("#email-newsletter-subscribe");
    $nav = $("#subscribe-nav");
    return $nav.bind("click", function(event) {
      event.preventDefault();
      return console.log("click!!!");
    });
  });

  $input.bind("focus", function() {
    return console.log("focus!!!");
  });

}).call(this);
