// Generated by CoffeeScript 1.6.3
(function() {
  $(document).ready(function() {
    var $input, $nav, $subscribe, allowFormSubmission, emailInvalid, emailValid, removeFormSubmission, submitForm;
    $nav = $("#subscribe-nav");
    $subscribe = $(".subscribe");
    $input = $("#email-newsletter-subscribe");
    $nav.bind("click", function(event) {
      event.preventDefault();
      $subscribe.show();
      return $input.focus();
    });
    $input.bind("keyup", function() {
      var email, emailReg;
      emailReg = /^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
      email = $input.val();
      if (emailReg.test(email)) {
        return emailValid();
      } else {
        return emailInvalid();
      }
    });
    emailValid = function() {
      $input.attr('style', 'color: green;');
      return allowFormSubmission();
    };
    emailInvalid = function() {
      $input.attr('style', 'color: #880000;');
      return removeFormSubmission();
    };
    allowFormSubmission = function() {
      var enterKey;
      enterKey = 13;
      return $input.bind('keydown', function(event) {
        if (event.which === enterKey) {
          return submitForm();
        }
      });
    };
    removeFormSubmission = function() {
      return $input.unbind("keydown");
    };
    return submitForm = function() {
      return console.log('form submitted!');
    };
  });

}).call(this);
