source "https://rubygems.org"

ruby "2.1.1"

gem "jekyll",   "~> 1.3.0"
gem "debugger", "~> 1.6.6"

# --------- Server  --------- #
gem 'rack-jekyll',  "~> 0.4.1"
gem "passenger",    "~> 4.0.37"
gem "rack-contrib", "~> 1.1.0"

gem "s3_website",   "~> 1.7.0"

# --------- Dev helpers  --------- #
group :development do
  gem "rake"
end

# --------- Assets  --------- #
group :development do
	gem "guard"
	gem "juicer"
  gem "coffee-script",      "~> 2.2.0"
  gem "sass",               "~> 3.3.0"
  gem "uglifier",           "~> 2.3.1"
  gem "guard-coffeescript", "~> 1.4.0"
  gem "guard-sass"
  gem "guard-livereload",   "~> 1.4.0"
  gem "guard-process",      "~> 1.0.6"
  gem "guard-uglify",       "~> 0.1.0"
end

# --------- Code snippet highlights  --------- #
gem "rubypython",  "~> 0.6.3"
gem "pygments.rb", "~> 0.5.4"