// Generated by CoffeeScript 1.6.3
(function() {
  $(document).ready(function() {
    return $(".card").bind("touchstart click", function() {
      return window.location.href = $(this).find('a').attr('href');
    });
  });

}).call(this);
