source "https://rubygems.org"

ruby "2.0.0"

gem "sinatra",  "~> 1.4.5"
gem "debugger", "~> 1.6.6"

# --------- Server  --------- #
gem "passenger",    "~> 4.0.37"
gem "rack-contrib", "~> 1.1.0"

gem "s3_website",   "~> 1.7.0"

# --------- Database  --------- #

gem "sequel",         "~> 4.11.0"
gem "sinatra-sequel", "~> 0.9.0"
gem "pg",             "~> 0.17.1"
gem "sqlite3",        "~> 1.3.9"

# --------- Dev helpers  --------- #
group :development do
  gem "rake", "~> 10.3.2"
  # gem "guard"
end

# --------- Testing  --------- #

group :development, :test do
  gem "rspec",     "~> 3.0.0"
  gem "rack-test", "~> 0.6.2"
end